/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface MerkleInterface extends ethers.utils.Interface {
  functions: {
    "getRoot()": FunctionFragment;
    "hashes(uint256)": FunctionFragment;
    "verify(bytes32[],bytes32,bytes32,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getRoot", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "hashes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BytesLike[], BytesLike, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getRoot", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hashes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {};
}

export class Merkle extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MerkleInterface;

  functions: {
    getRoot(overrides?: CallOverrides): Promise<[string]>;

    "getRoot()"(overrides?: CallOverrides): Promise<[string]>;

    hashes(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    "hashes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    verify(
      proof: BytesLike[],
      root: BytesLike,
      leaf: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "verify(bytes32[],bytes32,bytes32,uint256)"(
      proof: BytesLike[],
      root: BytesLike,
      leaf: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  getRoot(overrides?: CallOverrides): Promise<string>;

  "getRoot()"(overrides?: CallOverrides): Promise<string>;

  hashes(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "hashes(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  verify(
    proof: BytesLike[],
    root: BytesLike,
    leaf: BytesLike,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "verify(bytes32[],bytes32,bytes32,uint256)"(
    proof: BytesLike[],
    root: BytesLike,
    leaf: BytesLike,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    getRoot(overrides?: CallOverrides): Promise<string>;

    "getRoot()"(overrides?: CallOverrides): Promise<string>;

    hashes(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "hashes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    verify(
      proof: BytesLike[],
      root: BytesLike,
      leaf: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "verify(bytes32[],bytes32,bytes32,uint256)"(
      proof: BytesLike[],
      root: BytesLike,
      leaf: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getRoot(overrides?: CallOverrides): Promise<BigNumber>;

    "getRoot()"(overrides?: CallOverrides): Promise<BigNumber>;

    hashes(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "hashes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verify(
      proof: BytesLike[],
      root: BytesLike,
      leaf: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "verify(bytes32[],bytes32,bytes32,uint256)"(
      proof: BytesLike[],
      root: BytesLike,
      leaf: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getRoot(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getRoot()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hashes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hashes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verify(
      proof: BytesLike[],
      root: BytesLike,
      leaf: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "verify(bytes32[],bytes32,bytes32,uint256)"(
      proof: BytesLike[],
      root: BytesLike,
      leaf: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
