/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { Authorizable } from "../Authorizable";

export class Authorizable__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Authorizable> {
    return super.deploy(overrides || {}) as Promise<Authorizable>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Authorizable {
    return super.attach(address) as Authorizable;
  }
  connect(signer: Signer): Authorizable__factory {
    return super.connect(signer) as Authorizable__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Authorizable {
    return new Contract(address, _abi, signerOrProvider) as Authorizable;
  }
}

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "who",
        type: "address",
      },
    ],
    name: "authorize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "authorized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "who",
        type: "address",
      },
    ],
    name: "deauthorize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "who",
        type: "address",
      },
    ],
    name: "isAuthorized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "who",
        type: "address",
      },
    ],
    name: "setOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50600080546001600160a01b03191633179055610343806100326000396000f3fe608060405234801561001057600080fd5b50600436106100625760003560e01c806313af40351461006757806327c97fa51461008f5780638da5cb5b146100b5578063b6a5d7de146100d9578063b9181611146100ff578063fe9fbb8014610139575b600080fd5b61008d6004803603602081101561007d57600080fd5b50356001600160a01b031661015f565b005b61008d600480360360208110156100a557600080fd5b50356001600160a01b03166101d3565b6100bd610246565b604080516001600160a01b039092168252519081900360200190f35b61008d600480360360208110156100ef57600080fd5b50356001600160a01b0316610255565b6101256004803603602081101561011557600080fd5b50356001600160a01b03166102b3565b604080519115158252519081900360200190f35b6101256004803603602081101561014f57600080fd5b50356001600160a01b03166102c8565b6000546001600160a01b031633146101b1576040805162461bcd60e51b815260206004820152601060248201526f29b2b73232b9103737ba1037bbb732b960811b604482015290519081900360640190fd5b600080546001600160a01b0319166001600160a01b0392909216919091179055565b6000546001600160a01b03163314610225576040805162461bcd60e51b815260206004820152601060248201526f29b2b73232b9103737ba1037bbb732b960811b604482015290519081900360640190fd5b6001600160a01b03166000908152600160205260409020805460ff19169055565b6000546001600160a01b031681565b6000546001600160a01b031633146102a7576040805162461bcd60e51b815260206004820152601060248201526f29b2b73232b9103737ba1037bbb732b960811b604482015290519081900360640190fd5b6102b0816102e6565b50565b60016020526000908152604090205460ff1681565b6001600160a01b031660009081526001602052604090205460ff1690565b6001600160a01b03166000908152600160208190526040909120805460ff1916909117905556fea2646970667358221220e8e0348f61954a808528e9f772601eb1958f757040e9498718f601c80f6771ef64736f6c63430007010033";
